apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfsback-pv-claim
  namespace: nfs
  labels:
    edu.my.srv: nfsback
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi

