apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nfs
  namespace: nfs
spec:
  selector:
    matchLabels:
      app: "nfs"
  replicas: 1
  template:
    metadata:
      labels:
        app: "nfs"
    spec:
      containers:
        - name: nfs
          image: gcr.io/google_containers/volume-nfs:latest
          volumeMounts:
            - mountPath: /exports
              name: ocdata
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
      volumes:
        - name: ocdata
          persistentVolumeClaim:
            claimName: nfsback-pv-claim
