apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfspv
  labels:
    app: "nfspv"
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.59.253.118
    path: "/"
